name: Publish Lambda
on:
  push:
    branches: main
    paths:
      - "lambdas/**"
      - "package.json"
      - ".github/workflows/lambda.yaml"

env:
  API_GATEWAY_ID: ${{ secrets.API_GATEWAY_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  PASSWORD_SECRET_KEY: ${{ secrets.PASSWORD_SECRET_KEY }}
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_EMAIL: dvargas92495@gmail.com
  ROAMJS_EXTENSION_ID: multiplayer

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: install
        run: npm install
      - name: Deploy
        run: npm run lambdas
